name: Build Unreal Engine 5

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # UE5 só compila no Windows

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Unreal Engine
        run: |
          echo "Instalando UE5"
          choco install unreal-engine --version=5.0

      - name: Compilar Projeto Unreal
        run: |
          & "C:\Program Files\Epic Games\UE_5.0\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun -project="MyGame.uproject" -platform=Win64 -clientconfig=Development -build
